### ISSUE TITLE
PDT response cart line item order incorrect

### ISSUE THREAD

**Issue by jaesoonis** [paypal/pdt-code-samples#13]
I've posted this on the API section but i'm posting it here as well as it may be a PDT issue,

https://github.com/paypal/PayPal-REST-API-issues/issues/110

==================================================
So then, i've come across an issue on PROD that i've never encountered on the Sandbox environment.

Now i'm not sure if this is an API issue or an issue with PDT or IPN.

I'm currently using C# and the PayPal REST API to create a PayPal payment.

I add in 2 items in the cart thinking that the items sent will be in order as I need to do some processing once the transaction gets completed.

During sandbox testing, every item always came in the exact order as they were added into the Items list which was fine as I needed the first item to be a specific value and the second to be another specific value.

On PROD, i can see that the list is sent in the correct order, but sometimes when the PDT token is received (after confirming the payment ID and getting the transaction ID from it), the item order in the cart flips around which throws off my calculations.

Sending in the list - i expect it to be in this order - 1 then 2,

items = new List<Item>() { // Item 1. new Item() { name = "1", price = "1", currency = "USD", quantity = "1", sku = "1", description = "This is Spongebob", }, // Item 2 new Item() { name = "2", price = "2", currency = "USD", quantity = "2", sku = "2", description = "This is Patrick", }, }

And when the PDT gets called, it returns the items in an incorrect order
item_number1=2 item_number2=1 item_name1=2 item_name2=1
And when IPN is called, it returns the items in the correct order
item_number1=1 item_number2=2 item_name1=1 item_name2=2

IPN is consistently passing through the correct values but PDT is sometimes sending through the right order, sometimes sending through the incorrect order.

I can't reliably replicate this as it's never happened on the sandbox environment during testing and only happened in PROD which means I have to use real money to test

Are cart item order not guaranteed? Is that done by design?

**Comment by xiaoleih41** [comment]
Close this issue as you no longer need this feature.
