### ISSUE TITLE
php code contains errors 

### ISSUE THREAD

**Issue by dave-watts** [paypal/pdt-code-samples#2]
please check the php code example particularly the string concatenation with variable parts as they are in error

eg

curl_setopt($ch, CURLOPT_HTTPHEADER, array("Host: $pp_hostname"));

should be 

curl_setopt($ch, CURLOPT_HTTPHEADER, array("Host:".$pp_hostname));

**Comment by bg17aw** [comment]
There's nothing wrong with "Host: $pp_hostname", check this:

`$pp_hostname = "www.paypal.com";
echo "Host: $pp_hostname";`

**Comment by overint** [comment]
There's not a problem here, since you can include variables include double quoted strings.

**Comment by bg17aw** [comment]
good choice
